name: Pull Request

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install
        run: npm install

      - name: Check format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
