name: Pull Request

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install
        run: npm install

      - name: Check format
        run: npm run format:check

      - name: Check commit messages
        if: github.event_name == 'pull_request'
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
