name: Release Obsidian plugin

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create ZIP of release
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r format-with-prettier.zip main.js manifest.json

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            -F CHANGELOG.md \
            --draft \
            format-with-prettier.zip main.js manifest.json
